#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

cmd_found () { command -v "$@" >/dev/null; }
cmd_not_found() { ! cmd_found "$@"; }

# Install dependencies depending on OS
    
    # General
    cmd_not_found antibody && echo "Installing antibody" && (curl -sfL git.io/antibody | sh -s - -b /usr/local/bin)
    cmd_not_found starship && echo "Installing Starship" && sh -c "$(curl -fsSL https://starship.rs/install.sh)"

    # Fedora
    if cmd_found dnf; then
        echo "Installing Fedora dependencies"

        # Install dependencies
        sudo dnf install exa fzf bat neovim python3-neovim nodejs w3m mutt direnv podman ripgrep rbenv gh et

        # Font
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
    fi

    # macOS
    if cmd_found brew; then
        echo "Installing MacOS dependencies"

        # Install dependencies
        brew install exa fzf bat neovim node gawk w3m mutt direnv podman ripgrep rbenv tmuxinator gh MisterTea/et/et

        # Font
        if [ ! -d "/Library/Fonts/JetBrains Mono Regular Nerd Font Complete Mono.ttf"]; then
            brew tap homebrew/cask-fonts
            brew reinstall --cask font-jetbrains-mono
        fi

        # Enable python plugins
        python3 -m pip install --user --upgrade pynvim

        yes n | $(brew --prefix)/opt/fzf/install
    fi

    # All OS's
    pip3 install podman-compose

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    -c "${CONFIG}" \
    "${@}"

