right_format = "$time"

[username]
style_user = "bold blue"
show_always = true

[directory]
truncation_length = 10

[hostname]
ssh_only = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[time]
format = "[$time]($style) "
time_format = "%l:%M%P"
disabled = false
utc_time_offset = "-5"

